



        [
        {
          "barCodeId": "iiiii",
          "id": "175",
          "name": "lllllllllllll",
          "productCategory": "uuu",
          "rate": "909023.0"
        },
         {
          "barCodeId": "294",
          "id": "179",
          "name": "Dill",
          "productCategory": "?",
          "rate": "0.0"
        },
        {
          "barCodeId": "233123456",
          "id": "190",
          "name": "HP Desktop",
          "productCategory": "Electronics",
          "rate": "25.0"
        },
         {
          "barCodeId": "ASAS",
          "id": "208",
          "name": "WOOD",
          "productCategory": "AA",
          "rate": "4.2"
        },
        {
          "barCodeId": "pol",
          "id": "211",
          "name": "fgh",
          "productCategory": "CC",
          "rate": "4.0"
        },
         {
          "barCodeId": "1111111",
          "id": "217",
          "name": "orange",
          "productCategory": "tv",
          "rate": "10.0"
        }
        ] 