#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/4f3d94ee-57a8-427e-9044-4d0bb9a21fd6/ # 
title: retail
traits:
  responseMessage:
    responses:
      400:
        body:
          application/json:
            example:
              {"message":"<<bad request>>"}
/products: 
  get:
    responses: 
     200:
      body:
        application/json:
         example: |
          
          [
          {
          "barCodeId": "294",
          "id": "179",
          "name": "Dill",
          "productCategory": "?",
          "rate": "0.0"
          },
          {
          "barCodeId": "233123456",
          "id": "190",
          "name": "HP Desktop",
          "productCategory": "Electronics",
          "rate": "25.0"
          },
          {
          "barCodeId": "ASAS",
          "id": "208",
          "name": "WOOD",
          "productCategory": "AA",
          "rate": "4.2"
          },
          {
          "barCodeId": "pol",
          "id": "211",
          "name": "fgh",
          "productCategory": "CC",
          "rate": "4.0"
          },
          {
          "barCodeId": "1111111",
          "id": "217",
          "name": "orange",
          "productCategory": "tv",
          "rate": "10.0"
          }
          ] 

  post:
    responses: 
     201:
      body:
        application/json:
         examples:
           {
          "barCodeId": "111665",
          "id": "2997",
          "name": "Range rover",
          "productCategory": "car",
          "rate": "100"
          }
            
  /{id}:
    get:
      responses:
       200:
        body:
         application/json:
          example: 
            {
          "barCodeId": "pol",
          "id": "211",
          "name": "fgh",
          "productCategory": "CC",
          "rate": "4.0"
            }
    put:
      description: update by id
      responses: 
       200:
        body:
         application/json:
          example: 
            {
          "barCodeId": "pol",
          "id": "211",
          "name": "fgh",
          "productCategory": "CC",
          "rate": "4.0"
            }
    delete:
     body: 
      application/json:
    is: [responseMessage]
/bills:
  get:
    responses:
       200:
        body:
         application/json:
          example: |
          
           [
             {
               "id": "dc443",
                "type": "sale",
                "amount": 80000
             },
             {
               "id": "dc543",
                "type": "refund",
                "amount": 60000
             },
             {
               "id": "dc6445",
                "type": "profit",
                "amount": 100000
             },{
               "id": "dc465",
                "type": "sale",
                "amount": 90000
             }
           ]
  /{id}:
    get:
      responses:
       200:
        body:
         application/json:
          examples: 
             {
               "id": "dc443",
                "type": "sale",
                "amount": 80000
             }
    post:
      responses: 
       200:
        body:
         application/json:
          examples: 
            {
               "id": "dx343",
                "type": "profit",
                "amount": 99000
             }
           
      body: 
       application/json:
    is: [responseMessage]
    put:
      responses:
       200:
        body:
         application/json:
          example: 
             {
               "id": "dc443",
                "type": "sale",
                "amount": 99999
             }
      body: 
       application/json:
      is: [responseMessage]
    delete:
      responses:
       200:
        body:
         application/json:
          example: {"message":"successfully deleted"}
      body: 
       application/json:
      is: [responseMessage] 
/productcatagory:
  get:
    responses:
       200:
        body:
         application/json:
          example: |
           
           [ {
                  "id": "4",
                  "name": "?"
                  },
                 {
                     "id": "6",
                      "name": "?"
                       },
                      {
                     "id": "10",
                     "name": "?"
                       },
                         {
                        "id": "43",
                       "name": "?"
                       },
                     {
                    "id": "101",
                      "name": "TV"
                     },
                    {
                     "id": "102",
                      "name": "TV"
                      },
                      {
                        "id": "155",
                         "name": "watermillon"
                       }
           ]
  /{id}:
    get:
     responses:
       200:
        body:
         application/json:
          example: 
                {
                        "id": "155",
                         "name": "watermillon"
                }
    put:
      responses:
       200:
        body:
         application/json:
          examples: 
                    {
                        "id": "155",
                         "name": "water"
                      }
      body: 
       application/json:
      is: [responseMessage]
    delete:
      responses:
       200:
        body:
         application/json:
          example: {"message":"successfully deleted"}
  post:
    responses: 
     200:
      body:
        application/json:
          example: 
            {
                        "id": "177",
                         "name": "comidoro"
                       }

  

  
    


  
    

